management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

chat:
  exchanges:
    input: "incoming-messages"

spring:
  application:
    name: "trending-topic-api"
  mvc:
    async:
      request-timeout: -1